### ISSUE TITLE
Processing a large amount of AivenApplications is slow 

### ISSUE THREAD

**Issue by tronghn** [nais/aivenator#54]
During en masse resynchronizations, the controller/client will slow to a halt. We assume this is due to one or more of the following:

- The `MaxConcurrentReconciles` controller option is unset, which defaults to 1
- The `CreateSecret()` method is slow. This can be due to:
    - some form of rate limiting of the kube-client that communicates with the apiserver
    - some form of rate limiting of the aiven operations (create or update service users)

We should investigate and apply remediations.

**Comment by tronghn** [comment]
The `Get` operation for Aiven ServiceUsers has a peak processing latency that falls within the 20-40 second bucket

**Comment by mortenlj** [comment]
The two major API operations involved are "get service details" and "get service user". There is also "delete service user" and "create service user", but they are relatively quick and can be ignored.

"get service details" returns a huge response (~5MB of JSON in one test), but is already being cached and should only happen once per service.

"get service user" is actually "list service users" under the hood, because the API doesn't have support for getting a sinle service user. That's why it's so slow, because it is always listing ~1000 service users with certificates and all, then iterating the list to get the one we want.

The change introduced in https://github.com/nais/aivenator/commit/54cc8b47d36bf52bd1564a6f58ec5b1a9817c823
explicitly calls "list service users", and then caches the results for 5 minutes.

At the same time, we already have a background operation that calls "list service users" every 5 minutes to get metrics on how many users there are. This operation has been modified to also update the cache, which should result in virtually all "get service user" calls to end up getting the value from the cache.
